#!/usr/bin/env python
# Don't run tests from the root repo dir.
# We want to ensure we're importing from the installed
# binary package not from the CWD.

import os
from subprocess import check_call

_dname = os.path.dirname

REPO_ROOT = _dname(_dname(_dname(os.path.abspath(__file__))))
os.chdir(os.path.join(REPO_ROOT, 'tests'))


def run(command, env=None):
    return check_call(command, shell=True, env=env)


run('nosetests --with-coverage --cover-erase --cover-package s3transfer '
    '--with-xunit --cover-xml -v unit/ functional/')

# Run the serial implementation of s3transfer
os.environ['USE_SERIAL_IMPLEMENTATION'] = 'True'
run('nosetests -v functional/', env=os.environ)
